export const VERSION='2.1.1';
export const channels={
  global:{label:'全球',short:'INTL',band:'SW',freq:'9.650',delay:'2至7天',scope:'全球感染、跨国交通通信、国际医疗、人道援助。不得出现暮迟市街区级即时信息。'},
  china:{label:'中国',short:'CN',band:'SW',freq:'7.210',delay:'6至36小时',scope:'跨区域避难、交通、供水、防疫、救援与公开医疗进展。'},
  muchi:{label:'暮迟市',short:'MUCHI',band:'FM',freq:'88.7',delay:'数分钟至12小时',scope:'暮迟市道路桥梁、供水供电、天气、通信、避难点与普通幸存者信息。'}
};
const KEY='muchi_radio_v2';
const defaults={settings:{mode:'main',proxyPreset:'',apiUrl:'',apiKey:'',rememberKey:false,model:'',source:'openai',temperature:.72,maxTokens:520,auto:true,hours:6,dateRefresh:true,locationRefresh:true,autoChannel:'context',historyLimit:60,syncMvu:true,civilian:28,tension:'balanced',repeatGuard:true,extra:'',sound:true,static:32,scale:100,inline:true,showEmpty:true},state:{channel:'muchi',power:true,mute:false,light:true,hold:false,volume:48,lastStamp:'',lastLocation:'',rotate:0},history:[]};
export const store=structuredClone(defaults);
let sessionKey='',busy=false,render=()=>{},audio=null;
const clamp=(n,a,b)=>Math.min(b,Math.max(a,Number(n)||0));
export const isBusy=()=>busy;
export const setRenderer=fn=>{render=typeof fn==='function'?fn:()=>{}};
export const getApiKey=()=>sessionKey||(store.settings.rememberKey?store.settings.apiKey:'');
export const setApiKey=v=>{sessionKey=String(v||'')};
export function load(){try{const v=getVariables?.({type:'script'})?.[KEY];if(v){store.settings={...defaults.settings,...v.settings};store.state={...defaults.state,...v.state};store.history=Array.isArray(v.history)?v.history:[]}if(store.settings.rememberKey)sessionKey=store.settings.apiKey||''}catch(e){console.warn('[MR-87] load',e)}}
export function save(){try{const copy=structuredClone(store);copy.settings.apiKey=copy.settings.rememberKey?(sessionKey||copy.settings.apiKey||''):'';copy.history=copy.history.slice(0,clamp(copy.settings.historyLimit,10,200));updateVariablesWith?.(v=>{v[KEY]=copy;return v},{type:'script'})}catch(e){console.warn('[MR-87] save',e)}}
export async function world(){try{await waitGlobalInitialized?.('Mvu')}catch{}let v={};try{v=getVariables?.({type:'message',message_id:'latest'})||{}}catch{}const d=v.stat_data||v||{},w=d.世界||{},r=d.广播||{};return{date:String(w.当前日期||'2031-05-07'),time:String(w.当前时间||'19:18'),day:Number(w.生存天数||1),location:String(w.当前地点||'地下安全屋'),area:String(w.当前区域||'老城区'),stage:String(w.当前剧情阶段||'灾变初期'),danger:Number(w.区域危险度??25),weather:String(w.天气||'未知'),cure:String(w.解药完成日期||'2031-11-03'),signal:String(r.信号状态||'一般')}}
const stamp=w=>`${w.date} ${w.time}`;
function hours(a,b){const p=s=>{const m=String(s).match(/^(\d{4})-(\d{2})-(\d{2})\s+(\d{1,2}):(\d{2})/);return m?Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5]):null},x=p(a),y=p(b);return x===null||y===null?0:Math.max(0,(y-x)/36e5)}
const recent=k=>store.history.filter(x=>x.channel===k).slice(0,7).map(x=>`- [${x.eventTime}] ${x.source}: ${x.summary}`).join('\n')||'暂无。';
function tone(){return store.settings.tension==='calm'?'偏生活化克制，重大消息很少。':store.settings.tension==='tense'?'允许偏紧张，但仍保持有限、可信、非任务化信息。':'保持真实公共广播节奏，大多数消息普通具体，偶尔出现重要变化。'}
function systemPrompt(){return `你是虚构末世世界“暮迟之昼”的无线电广播生成器。固定事实：灾变爆发2031-05-07；稳定解药完成日固定2031-11-03。此前不得宣布稳定解药完成，之后也不是社会瞬间恢复。沈挽昼与{{user}}只是普通幸存者，不是关键样本或救世主。广播不知道沈挽昼特殊感染、{{user}}实时位置、楚泽私人秘密。禁止给主角发布专属救世任务。广播允许普通、重复、滞后、失效；供水供电、天气、道路、通信等应占相当比例。不要提AI、变量、世界书或SillyTavern。`;}
function userPrompt(k,w){const c=channels[k];return `生成一条便携收音机广播。\n当前：${stamp(w)}，灾变第${w.day}日，地点${w.location}/${w.area}，危险${w.danger}/100，天气${w.weather}，阶段${w.stage}。\n频道：${c.label} ${c.band} ${c.freq}；延迟${c.delay}；范围：${c.scope}\n风格：${tone()} 民间/未经证实信息倾向约${store.settings.civilian}%。\n摘要30-90字；听写正文70-220字；可少量静电断句。事件时间不得晚于当前世界时间。\n近期内容，避免重复：\n${store.settings.repeatGuard?recent(k):'无需重复保护。'}\n附加偏好：${store.settings.extra||'无'}\n只输出结构化数据。`;}
const schema={name:'muchi_radio',strict:true,value:{type:'object',properties:{event_time:{type:'string'},source:{type:'string'},signal:{type:'string',enum:['强','一般','微弱','断续']},category:{type:'string'},headline:{type:'string'},summary:{type:'string'},transcript:{type:'string'},certainty:{type:'string'}},required:['event_time','source','signal','category','headline','summary','transcript','certainty'],additionalProperties:false}};
function config(k,w){const s=store.settings,c={user_input:userPrompt(k,w),ordered_prompts:[{role:'system',content:systemPrompt()},{role:'user',content:userPrompt(k,w)}],should_silence:true,json_schema:schema,generation_id:`muchi-radio-${Date.now()}`};const sampling={temperature:clamp(s.temperature,0,2),max_tokens:clamp(s.maxTokens,128,1400)};if(s.mode==='proxy')c.custom_api={proxy_preset:s.proxyPreset,model:s.model||undefined,...sampling};else if(s.mode==='custom')c.custom_api={apiurl:s.apiUrl,key:getApiKey(),model:s.model,source:s.source||'openai',...sampling};else c.custom_api={...sampling};return c}
function parse(x){const t=typeof x==='string'?x:(x?.content||JSON.stringify(x)),clean=t.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(clean)}catch{}const m=clean.match(/\{[\s\S]*\}/);if(!m)throw Error('模型未返回JSON');return JSON.parse(m[0])}
async function syncMvu(x){if(!store.settings.syncMvu)return;try{updateVariablesWith?.(v=>{const d=v.stat_data||(v.stat_data={}),r=d.广播||(d.广播={}),label=channels[x.channel].label;r.当前频道=label;r.信号状态=x.signal;r.上次刷新时间=x.worldStamp;const sec=r[label]||(r[label]={});sec.事件时间=x.eventTime;sec.来源=x.source;sec.摘要=x.summary;return v},{type:'message',message_id:'latest'})}catch(e){console.warn('[MR-87] MVU sync',e)}}
export async function generate(k=store.state.channel,reason='manual'){if(busy)return;busy=true;render('busy',true);noise(.35);try{const w=await world(),raw=parse(await generateRaw(config(k,w))),x={id:`r${Date.now()}`,channel:k,eventTime:String(raw.event_time||stamp(w)),source:String(raw.source||channels[k].label),signal:['强','一般','微弱','断续'].includes(raw.signal)?raw.signal:'一般',category:String(raw.category||'其他'),headline:String(raw.headline||'广播更新'),summary:String(raw.summary||raw.transcript||''),transcript:String(raw.transcript||raw.summary||''),certainty:String(raw.certainty||'官方通报'),worldStamp:stamp(w),location:w.location};store.history.unshift(x);store.history=store.history.slice(0,clamp(store.settings.historyLimit,10,200));store.state.channel=k;store.state.lastStamp=x.worldStamp;store.state.lastLocation=w.location;save();await syncMvu(x);render('all');if(reason==='manual')toastr?.success?.(`收到新的${channels[k].label}广播`)}catch(e){console.error('[MR-87]',e);render('error',e?.message||String(e));toastr?.error?.(`收音机生成失败：${e?.message||e}`)}finally{busy=false;render('busy',false)}}
export async function autoRefresh(){if(!store.settings.auto||busy)return;const w=await world(),now=stamp(w),prev=store.state.lastStamp;let why='';if(!prev){store.state.lastStamp=now;store.state.lastLocation=w.location;save();return}if(store.settings.dateRefresh&&prev.slice(0,10)!==now.slice(0,10))why='date';else if(store.settings.locationRefresh&&store.state.lastLocation&&store.state.lastLocation!==w.location)why='location';else if(hours(prev,now)>=clamp(store.settings.hours,1,48))why='time';if(!why)return;let k=store.state.channel;if(store.settings.autoChannel==='context'){if(why==='location')k='muchi';else if(why==='date')k=w.day<=10?'china':'global'}else if(store.settings.autoChannel==='rotate'){const a=['muchi','china','global'];store.state.rotate=(store.state.rotate+1)%a.length;k=a[store.state.rotate]}await generate(k,'auto')}
export const latest=k=>store.history.find(x=>x.channel===k);
export function switchChannel(k){if(!channels[k]||!store.state.power)return;store.state.channel=k;noise(.1);clickSound();save();render('radio')}
export function cycle(d){const a=['global','china','muchi'],i=a.indexOf(store.state.channel);switchChannel(a[(i+d+a.length)%a.length])}
export function clearHistory(){store.history=[];save();render('all')}
export function audioCtx(){if(!store.settings.sound||store.state.mute)return null;try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;audio ||= new A();if(audio.state==='suspended')audio.resume();return audio}catch{return null}}
export function clickSound(){const a=audioCtx();if(!a)return;const o=a.createOscillator(),g=a.createGain();o.type='square';o.frequency.value=165;g.gain.value=(store.state.volume/100)*.025;o.connect(g).connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.035);o.stop(a.currentTime+.04)}
export function noise(sec=.15){const a=audioCtx();if(!a)return;const n=Math.floor(a.sampleRate*sec),b=a.createBuffer(1,n,a.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=a.createBufferSource(),f=a.createBiquadFilter(),g=a.createGain();f.type='bandpass';f.frequency.value=1800;g.gain.value=(store.state.volume/100)*(store.settings.static/100)*.18;s.buffer=b;s.connect(f).connect(g).connect(a.destination);s.start()}
export async function testConnection(){const w=await world(),c=config(store.state.channel,w);c.user_input='只返回 RADIO_OK';c.ordered_prompts=[{role:'user',content:'只返回 RADIO_OK'}];delete c.json_schema;const x=await generateRaw(c),t=typeof x==='string'?x:(x?.content||'');if(!String(t).includes('RADIO_OK'))throw Error(String(t).slice(0,80));return true}
export async function initCore(){load();const w=await world();if(!store.state.lastStamp)store.state.lastStamp=stamp(w);if(!store.state.lastLocation)store.state.lastLocation=w.location;save()}
